# **Exercise**

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [ ]:
import numpy as np #import the NumPy library and use the shortcut name "np"

In [ ]:
np.__version__ #checking what version

'2.0.2'

#### **A.** Create an ndarry object (A) with any values from 1 to 100 in a nested Python List.

In [ ]:
A = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

Explanation: creates a NumPy array named A using a nested list to form 4 rows and 5 columns

In [ ]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Explanation: it prints the entire array A on the screen

In [ ]:
print(A.shape) # Display the dimensions of array A (number of rows and columns)

(4, 5)


Explanation: this shows the number of rows and columns in the array, which is (4, 5)

In [ ]:
print(A.max()) # Display the highest value found in array A

20


Explanation: finds and prints the largest value in the array using an array method, which is 20

In [ ]:
print(np.max(A))

20


Explanation: finds and prints the largest value in the array using a NumPy function

#### **B.** Create a 5x5 integer-array filled with ones.

In [ ]:
B = np.ones(((5,5)), dtype = int)

Explanation: this creates a 5x5 array filled with ones and ensures all values are integers

In [ ]:
print(B)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
print(B.shape)

(5, 5)


Explanation: this shows the shape of the array, which is 5 rows and 5 columns

In [ ]:
print(B.size)

25


Explanation: this shows the total number of elements in the array, which is 25

In [ ]:
print(B.ndim)

2


Explanation: this shows the number of dimensions of the array, which is 2 (rows and columns)

#### **C.** Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [ ]:
C = np.arange(-5, 6)

Explanation: this creates an array of values starting from -5 up to 5

In [ ]:
result = C * 2

Explanation: this multiplies each element in the array by 2

In [ ]:
print(result)

[-10  -8  -6  -4  -2   0   2   4   6   8  10]


Explanation: this prints the resulting array after multiplication

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd /content/drive/MyDrive/IS110_BPerformance_Deocampo/IS110_repo_Deocampo

/content/drive/MyDrive/IS110_BPerformance_Deocampo/IS110_repo_Deocampo


In [ ]:
%cd /content/drive/MyDrive/IS110_BPerformance_Deocampo

/content/drive/MyDrive/IS110_BPerformance_Deocampo


In [ ]:
pwd

'/content/drive/MyDrive/IS110_BPerformance_Deocampo'

In [3]:
!cp /content/drive/MyDrive/IS110_BPerformance_Deocampo/NumpyExercise /content/drive/MyDrive/IS110_BPerformance_Deocampo/IS110_repo_Deocampo/PythonEnvi_deocampo/Chapters_Deocampo

cp: cannot stat '/content/drive/MyDrive/IS110_BPerformance_Deocampo/NumpyExercise': No such file or directory
